### ISSUE TITLE
Aapply the good practices of psr1

### ISSUE THREAD

**Issue by gilglecio** [jetphp/jetphp#13]
- [x] Files MUST use only <?php and <?= tags.
- [x] Files MUST use only UTF-8 without BOM for PHP code.
- [x] Files SHOULD either declare symbols (classes, functions, constants, etc.) or cause side-effects (e.g. generate output, change .ini settings, etc.) but SHOULD NOT do both.
- [x] Namespaces and classes MUST follow an “autoloading” PSR: [PSR-0, PSR-4].
- [x] Class names MUST be declared in StudlyCaps.
- [x] Class constants MUST be declared in all upper case with underscore separators.
- [x] Method names MUST be declared in camelCase.

**Comment by gilglecio** [comment]
if everyone agrees, I'll start to make the issue, hug!

**Comment by JoaoArtur** [comment]
@gilglecio i'll change a few the core... because the jetphp default models are in the safe folder of development models. After that we can correct the standard recommendations
