### ISSUE TITLE
Proposta de união jetphp + FormDin + easyform

### ISSUE THREAD

**Issue by bjverde** [jetphp/jetphp#15]
Vou escrever em PT-BR mesmo.

@JoaoArtur , @gilglecio , @cassiogiehl 

Primeiro, parabéns pelo trabalho de vocês. Estou vendo que estão trabalhando firme no jetphp. 

A minha proposta é unir forças para desenvolver um FrameWork PHP para construção de sistemas. Algo que seja de fácil uso, produtivo e com diversos componentes prontos para o uso. Sem engessar o desenvolvedor, possibilitando a criação e compartilhamento de novos componentes.  

Os navegadores só entendem HTML, CSS e JavaScript. A cada dia a demanda por sistemas Web só cresce, obrigando o desenvolvedor saber uma quantidade cada vez maior de linguagens e tecnologia.  Tomando muito tempo e esforço repetitivo, isso sem falar que a cada 5 segundos aparece um FrameWork JavaScript. 

**A união dos esforço irá gerar um FrameWork melhor.** Possibilitando ao desenvolvedor com pouco conhecimento e/ou tempo entregar um sistema com grandes funcionalidades. 

Vi que um de vocês está falando de melhores praticas com PSR1, além disso muito ainda deve ser feito. Exemplo de algumas perguntas

- O foco será produtividade ou beleza ?
- Alguém já fez a parte de API Rest ? 
- Qual será o look and feel do Front-end ? BootStrap, Materialize, Vuetify ou talvez algo próprio 
- A documentação está pronta ? Em inglês e PT-BR
- Tem vídeo sobre ?
- Tem Aplicação de exemplo ?
- Tem exemplo de uso de cada um dos componentes ?

São 3 FrameWorks fazendo + ou - as mesmas coisas, gastando tempo e esforço. Vamos nos unir e fazer algo algo melhor.

Minha ideia é fazer tudo baseado no motor do [Element HTML](https://developer.mozilla.org/en-US/docs/Glossary/Element). 

![Element HTML](https://mdn.mozillademos.org/files/7659/anatomy-of-an-html-element.png)

O jetphp parece que não utiliza esse conceito. Porém o [FormDin](https://github.com/bjverde/formDin) e o [Easyform](https://github.com/cajudev/easyform) já estão utilizando. 

* Motor Element HTML no FormDin - https://github.com/bjverde/formDin/blob/master/base/classes/webform/TElement.class.php
 * Motor Element HTML no Easyform - https://github.com/cajudev/easyform/blob/master/src/Elements/Element.php

O uso desse motor com OO, possibilitar com facilidade deixar diversos componentes prontos o uso com pouco esforço. 

Exemplo do código para criar um grid simples

```php
$dados = $controller->selectAll();
$gride = new TGrid('gdTeste' // id do gride
                                ,'Lista de Pedidos'
                                );

$gride->setData( $dados ); // array de dados        
$gride->addColumn($PK, 'id Pedido');
$gride->addColumn('NOME_COMPRADOR','Nome do Comprador');
$gride->addColumn('DATA_PEDIDO', 'Data');
$gride->addColumn('FORMA_PAGAMENTO', 'Pagamento');

$frm->addHtmlField('gride', $gride);
```
![Grid](https://raw.githubusercontent.com/bjverde/formDin/be94cd60e0934cc0f9c34a3d00d65e03453873e8/documents/img/appteste_grid.png
)

Obs: 
1 - Acho que foi com o João que conversei algumas vezes no grupo do PHPBrasil do Faceboook. 

2 - Ainda não mandei Richard Lopes do EasyForm

3 - Atualmente o FormDin tem um gerador de código. Ele lê o banco de dados e gera a primeira versão do sistema com base no banco em minutos.

**Comment by bjverde** [comment]
Chamei o Richard Lopes do EasyForm https://github.com/cajudev/easyform/issues/1

**Comment by lopesrichard** [comment]
Onde podemos conversar? Slack, discord?

**Comment by bjverde** [comment]
Podem escolher o local ! Por mim pode ser até no Isseu do GitHub mesmo.

**Comment by bjverde** [comment]
@lopesrichard vamos iniciar a conversa aqui mesmo ??

Meu objetivo é ter um FrameWork para fazer sistemas web que seja facil de usar, com diversos componentes prontos e com um gerador de código. 

Algo semelhante ao [Adianti Frame](https://www.adianti.com.br/framework) e o [Adianti Builder](https://www.adiantibuilder.com.br/) só que totalmente Software Livre. 

Ahh FormDin 4 é baseado nas ideia do Pablo Dall'Oglio como pode ser visto [História do formDin](História do formDin)

**Comment by bjverde** [comment]
Sobre o uso do  [Element HTML](https://developer.mozilla.org/en-US/docs/Glossary/Element). Estava estudando e me parece a proxima etapa de desenvolvimento web é usar [Web Components](https://developer.mozilla.org/pt-BR/docs/Web/Web_Components).

Mais referencias sobre:
* https://tableless.com.br/web-components-introducao/
* https://www.youtube.com/watch?v=7Q0-E_rZ_Cc
* https://developers.google.com/web/fundamentals/web-components/customelements?hl=pt-br
* https://www.webcomponents.o

**Comment by lopesrichard** [comment]
Não tenho interesse em desenvolver um framework em si, mas tenho bastante interesse em desenvolver componentes que juntos podem vir a formar um framework, como é o caso do symphony. Minha ideia é ajudar as pessoas a fazerem mais com menos, e para isso essas ferramentas precisam ser adaptadas para um rápido aprendizado mantendo uma certa customização. Esta semana estudarem sobre esses web components e retorno com alguma opinião a respeito.

**Comment by lopesrichard** [comment]
Brinquei um pouco com esses web components e vejo que abre espaço pra várias possibilidades. Só que como envolve praticamente apenas javascript, teria que ver como php se encaixaria nesse meio.

**Comment by helhoso** [comment]
Otima discursão
Se alguns de vocês já leram meu código fonte vão ver que não sou um PHP expert, faço o necessário, quando preciso de algo pesquiso na internet e só utilizo o que consigo entender.
Amei isso: $frm->addHtmlField('gride', $gride); 
mas ainda não sei como implementar e se vai tornar o pacote muito grande
gosto de coisas simples e de fácil entendimento
para comunicação eu prefiro uma sala de bate-papo online ou uma vídeo-conferência, as coisas fluem mais rápido, aqui demora pra se ter respostas

Se alguem puder me ajudar com $frm->addHtmlField('gride', $gride); eu desejo incluir no framework que estou escrevendo.

**Comment by bjverde** [comment]
@helhoso vamos concentrar a comunicação no https://github.com/bjverde/formDin/issues/192  assim não bagunçamos o projetos de outras pessoas.

**Comment by helhoso** [comment]
Blz

**Comment by bjverde** [comment]
@ThiGaleno a classe TElement é motor do FormDin é dela que tudo nasce.
https://github.com/bjverde/formDin/blob/master/base/classes/webform/TElement.class.php

**Comment by helhoso** [comment]
pessoal como eu exibo as configurações do meu servidor xampp?
fiz isso a alguns dias mas não me lembro mais. eu tinha até uma pagina que rodava e ela exibia tudo que estava instalado no servidor.
desde já agradeço

**Comment by helhoso** [comment]
minha versão do PHP no Xampp é 5.6.15, quero mudar para 7
qual versão do PHP eu baixo
esta é a ultima php-7.3.10.tar.bz2 (sig) [14,624Kb]
dai em mais duas anteriores
php-7.3.10.tar.gz (sig) [19,132Kb]
php-7.3.10.tar.xz (sig) [11,804Kb]

**Comment by bjverde** [comment]
@helhoso vamos concentrar a comunicação no bjverde/formDin#192 assim não bagunçamos o projetos de outras pessoas. Lá vou responder suas perguntas
